
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p2c1.ReglasGram.DB;

/** CUP generated class containing symbol constants. */
public class symDB {
  /* terminals */
  public static final int N_E = 27;
  public static final int CAPTCHA = 6;
  public static final int LLAD = 8;
  public static final int POSICION = 21;
  public static final int CODIGO_HTML = 13;
  public static final int P_D = 28;
  public static final int IGUAL = 10;
  public static final int SEMI = 12;
  public static final int NOMBRE_CAPTCHA = 15;
  public static final int PROCEDIMIENTO = 26;
  public static final int ID = 9;
  public static final int TIPO = 23;
  public static final int DOS_PUNTOS = 3;
  public static final int STRING = 11;
  public static final int FALLOS = 18;
  public static final int EOF = 0;
  public static final int MODO = 25;
  public static final int LAST_FECHA = 19;
  public static final int LINK = 14;
  public static final int SIMBOLOS = 20;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int CANT_UTILIZADOS = 16;
  public static final int ACIERTOS = 17;
  public static final int PAI = 4;
  public static final int INVALID = 30;
  public static final int VALOR = 24;
  public static final int LLAI = 7;
  public static final int PAD = 5;
  public static final int CAPTCHAS = 2;
  public static final int P_D_E = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CAPTCHAS",
  "DOS_PUNTOS",
  "PAI",
  "PAD",
  "CAPTCHA",
  "LLAI",
  "LLAD",
  "ID",
  "IGUAL",
  "STRING",
  "SEMI",
  "CODIGO_HTML",
  "LINK",
  "NOMBRE_CAPTCHA",
  "CANT_UTILIZADOS",
  "ACIERTOS",
  "FALLOS",
  "LAST_FECHA",
  "SIMBOLOS",
  "POSICION",
  "IDENTIFICADOR",
  "TIPO",
  "VALOR",
  "MODO",
  "PROCEDIMIENTO",
  "N_E",
  "P_D",
  "P_D_E",
  "INVALID"
  };
}

