
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p2c1.ReglasGram.gcic;

/** CUP generated class containing symbol constants. */
public class symGCIC {
  /* terminals */
  public static final int INVALID = 56;
  public static final int C_P = 28;
  public static final int ID_INTEGER = 67;
  public static final int SEMI = 40;
  public static final int ASC = 57;
  public static final int ID_ELEMENT = 81;
  public static final int MEN_QUE = 49;
  public static final int ID_CHAR = 71;
  public static final int INIT = 75;
  public static final int C_GCIC = 3;
  public static final int DIFERENTE = 51;
  public static final int LETIMPAR_NUM = 60;
  public static final int PARAMETRO = 5;
  public static final int C_LINK = 13;
  public static final int C_OPTION = 22;
  public static final int THENWHILE = 80;
  public static final int C_SPAM = 18;
  public static final int THEN = 74;
  public static final int DOS_PUNTOS = 37;
  public static final int ID_DECIMAL = 70;
  public static final int ID_BOOLEAN = 69;
  public static final int C_BODY = 17;
  public static final int C_TEXTAREA = 20;
  public static final int REVERSE = 61;
  public static final int ALERT_INFO = 64;
  public static final int C_DIV = 23;
  public static final int C_HEAD = 12;
  public static final int COMA = 38;
  public static final int NUM_ALEATORIO = 63;
  public static final int HUNTIL = 78;
  public static final int ENTERO = 53;
  public static final int C_SCRIPTING = 29;
  public static final int MAY_QUE = 50;
  public static final int STRING_WS = 8;
  public static final int C_INPUT = 19;
  public static final int GET_ELEMENT_BY_ID = 47;
  public static final int IGUAL = 6;
  public static final int BARRA90 = 41;
  public static final int WHILE = 79;
  public static final int DECIMAL = 54;
  public static final int CHAR = 52;
  public static final int BOOLEAN = 55;
  public static final int PAI = 32;
  public static final int DIAG = 11;
  public static final int MULT = 45;
  public static final int CORI = 4;
  public static final int PAD = 33;
  public static final int ELSE = 73;
  public static final int MENOS = 44;
  public static final int CORD = 9;
  public static final int MAQ = 10;
  public static final int C_BR = 25;
  public static final int EOF = 0;
  public static final int INSERTAR = 34;
  public static final int SUMA = 43;
  public static final int C_TITLE = 14;
  public static final int LLAI = 35;
  public static final int REPEAT = 77;
  public static final int LLAD = 36;
  public static final int C_IMG = 24;
  public static final int NOMBRE_FUNCION = 31;
  public static final int error = 1;
  public static final int EXIT = 65;
  public static final int MENQ = 2;
  public static final int IF = 72;
  public static final int DESC = 58;
  public static final int IGUALACION = 48;
  public static final int ON_LOAD = 30;
  public static final int C_SELECT = 21;
  public static final int END = 76;
  public static final int STRING_TOTAL = 15;
  public static final int C_H1 = 27;
  public static final int ID_VARIABLE = 16;
  public static final int GLOBAL = 66;
  public static final int CARACTER_ALEATORIO = 62;
  public static final int INSERT = 46;
  public static final int ID_STRING = 68;
  public static final int STRING = 7;
  public static final int C_BUTTON = 26;
  public static final int ADMIRACION = 39;
  public static final int LETPAR_NUM = 59;
  public static final int AND_1 = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENQ",
  "C_GCIC",
  "CORI",
  "PARAMETRO",
  "IGUAL",
  "STRING",
  "STRING_WS",
  "CORD",
  "MAQ",
  "DIAG",
  "C_HEAD",
  "C_LINK",
  "C_TITLE",
  "STRING_TOTAL",
  "ID_VARIABLE",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_P",
  "C_SCRIPTING",
  "ON_LOAD",
  "NOMBRE_FUNCION",
  "PAI",
  "PAD",
  "INSERTAR",
  "LLAI",
  "LLAD",
  "DOS_PUNTOS",
  "COMA",
  "ADMIRACION",
  "SEMI",
  "BARRA90",
  "AND_1",
  "SUMA",
  "MENOS",
  "MULT",
  "INSERT",
  "GET_ELEMENT_BY_ID",
  "IGUALACION",
  "MEN_QUE",
  "MAY_QUE",
  "DIFERENTE",
  "CHAR",
  "ENTERO",
  "DECIMAL",
  "BOOLEAN",
  "INVALID",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "GLOBAL",
  "ID_INTEGER",
  "ID_STRING",
  "ID_BOOLEAN",
  "ID_DECIMAL",
  "ID_CHAR",
  "IF",
  "ELSE",
  "THEN",
  "INIT",
  "END",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "ID_ELEMENT"
  };
}

