
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p2c1.ReglasGram.insert;

/** CUP generated class containing symbol constants. */
public class symInsert {
  /* terminals */
  public static final int CORI = 3;
  public static final int DIAG = 10;
  public static final int C_DIV = 16;
  public static final int IGUAL = 5;
  public static final int CORD = 8;
  public static final int C_BR = 18;
  public static final int C_SPAM = 11;
  public static final int C_OPTION = 15;
  public static final int MENQ = 2;
  public static final int C_SELECT = 14;
  public static final int STRING = 6;
  public static final int C_IMG = 17;
  public static final int EOF = 0;
  public static final int C_P = 21;
  public static final int error = 1;
  public static final int C_TEXTAREA = 13;
  public static final int C_INPUT = 12;
  public static final int INVALID = 22;
  public static final int C_BUTTON = 19;
  public static final int PARAMETRO = 4;
  public static final int STRING_WS = 7;
  public static final int C_H1 = 20;
  public static final int MAQ = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENQ",
  "CORI",
  "PARAMETRO",
  "IGUAL",
  "STRING",
  "STRING_WS",
  "CORD",
  "MAQ",
  "DIAG",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_P",
  "INVALID"
  };
}

